// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_500.tsx";
import * as $2 from "./routes/about/index.tsx";
import * as $3 from "./routes/api/geolocation.ts";
import * as $4 from "./routes/index.tsx";
import * as $$0 from "./islands/HistoryButton.tsx";
import * as $$1 from "./islands/forms/DimensionsForm.tsx";
import * as $$2 from "./islands/structure/NavBar.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_500.tsx": $1,
    "./routes/about/index.tsx": $2,
    "./routes/api/geolocation.ts": $3,
    "./routes/index.tsx": $4,
  },
  islands: {
    "./islands/HistoryButton.tsx": $$0,
    "./islands/forms/DimensionsForm.tsx": $$1,
    "./islands/structure/NavBar.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
